name: jellyfin-hackwae

services:
  app:
    image: linuxserver/jellyfin:10.11.6
    restart: unless-stopped

    ports:
      - target: 8096
        published: 8096
        protocol: tcp

    volumes:
      - type: bind
        source: /DATA/AppData/jellyfin/config
        target: /config
      - type: bind
        source: /DATA/Media
        target: /data

x-casaos:
  architectures:
    - amd64

  main: app

  category: Media

  port_map: "8096"

  scheme: http

  index: /

  webui: http://[HOST]:[PORT]

  title:
    en_us: Jellyfin HackWae

  description:
    en_us: Jellyfin for HackWae homelab

  developer: HackWae
