name: jellyfin-hackwae

services:
  app:
    image: linuxserver/jellyfin:10.11.6
    restart: unless-stopped

    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Makassar
      JELLYFIN_PublishedServerUrl: ''

    ports:
      - target: 8096
        published: 8096
        protocol: tcp

    volumes:
      - type: bind
        source: /DATA/AppData/jellyfin/config
        target: /config
      - type: bind
        source: /DATA/Media
        target: /data/movies


x-casaos:
  store_app_id: jellyfin-hackwae
  architectures:
    - amd64
    - arm64
  main: app
  category: HackWae-Appstore
  port_map: "8096"
  scheme: http
  index: /
  webui: http://[HOST]:[PORT]
  envs:
    - container: PUID
      description:
        en_us: UID for volume owner
    - container: PGID
      description:
        en_us: GID for volume owner
    - container: TZ
      description:
        en_us: Container timezone
    - container: JELLYFIN_PublishedServerUrl
      description:
        en_us: Optional published URL
  icon: https://raw.githubusercontent.com/WaeTechDesign/casaos-appstore/main/Apps/icon/jellyfin.png
  thumbnail: https://raw.githubusercontent.com/WaeTechDesign/casaos-appstore/main/Apps/icon/jellyfin.png
  title:
    en_us: Jellyfin HackWae
  description:
    en_us: Jellyfin for HackWae homelab
  developer: HackWae
