name: jellyfin-hackwae

services:
  app:
    image: linuxserver/jellyfin:10.11.6
    restart: unless-stopped

    ports:
      - target: 8096
        published: 8096
        protocol: tcp

    volumes:
      - type: bind
        source: /DATA/AppData/jellyfin/config
        target: /config
      - type: bind
        source: /DATA/Media
        target: /data

x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  category: Media
  port_map: "8096"
  scheme: http
  index: /
  webui: http://[HOST]:[PORT]
  icon: https://raw.githubusercontent.com/WaeTechDesign/casaos-appstore/refs/heads/main/Apps/icon/jellyfin.png
  thumbnail: https://raw.githubusercontent.com/WaeTechDesign/casaos-appstore/refs/heads/main/Apps/icon/jellyfin.png
  title:
    en_us: Jellyfin HackWae
  description: 'Jellyfin is a Free Software Media System that puts you in control of managing and streaming your media. It is an alternative to the proprietary Emby and Plex, to provide media from a dedicated server to end-user devices via multiple apps. Jellyfin is descended from Emby''s 3.5.2 release and ported to the .NET Core framework to enable full cross-platform support. There are no strings attached, no premium licenses or features, and no hidden agendas: just a team who want to build something better and work together to achieve it.'
  tagline:
    en_us: Jellyfin for HackWae homelab
  developer: HackWae
